server:
  port: 9527

spring:
  application:
    name: IBUY-ZUUL

zuul:
  ignoredServices: '*' #只能通过路由访问，不能使用服务名访问
  routes:
    plat:
      serviceId: IBUY-PLAT
      path: /plat/**
  prefix: /services